<h1 align=center style="line-height:200%;font-family:vazir;color:#0099cc">
<font face="vazir" color="#0099cc">
دوچرخه سواران کم‌طاقت
</font>
</h1>


<p dir=rtl style="direction: rtl;text-align: right;line-height:200%;font-family:vazir;font-size:medium">
<font face="vazir" size=3>
یوسف، صاحب یک کسب و کار اجاره‌ی دوچرخه در پارک همیشه‌سبز (که همیشه هم سبز نیست) است!
او بعد از مدتی متوجه شد که در برخی روزها مشتریان دوچرخه‌ها خیلی از دمای هوا شکایت می‌کنند به طوری که به نظر می‌آید میانگین دمایی که مشتریان احساس می‌کنند با دمای واقعی تفاوت دارد. با آن که یوسف بسیار سعی کرد دوچرخه سواران را قانع کند که دمای هوا با آن‌چه آنان تصور می‌کنند متفاوت است، در نهایت تسلیم مشتریان شده و تصمیم گرفت تا خود سیستمی برای پیش‌بینی دمایی که واقعا احساس می‌شود بسازد تا بتواند خدمات بهتری به مشتریان ارائه داده و سود بیشتری بکند.
<br>
مسلما خود یوسف حوصله‌ی نوشتن این سیستم را ندارد بنابراین از شما برای انجام این کار کمک خواست.
    </font>
</p>

In [2]:
import pandas as pd
import numpy as np
from numpy import nan as NA


<p dir=rtl style="direction: rtl;text-align: right;line-height:200%;font-family:vazir;font-size:medium">
<font face="vazir" size=3>
یوسف بعد از صحبت با دوچرخه سواران متوجه شد که دمایی که احساس می‌کنند معمولا با سرعت باد و رطوبت هوا رابطه‌ی مستقیم دارد؛
بنابراین این اطلاعات را نیز در سیستم خود ثبت کرد با بتوانید از آن‌ها استفاده کنید.
<br>
با اجرای سلول زیر، می‌توانید دیتافریمی که یوسف ثبت کرده است را به طور کامل لود کنید. این دیتافریم شامل ستون‌های زیر است:
<br>
    </font>
</p>

<p dir=rtl style="direction: rtl;text-align: right;line-height:200%;font-family:vazir;font-size:medium">
<table dir=rtl align = center>

<tr>
    <th><font face="vazir" size=3>نام ستون</th>
    <th><font face="vazir" size=3>توضیح</th>
</tr>

<tr>
    <td><font face="vazir" size=3>cnt</td>
    <td><font face="vazir" size=3>تعداد دوچرخه‌هایی که در روز اجاره گرفته شده‌اند</td>
</tr>
    
<tr>
    <td><font face="vazir" size=3>t1</td>
    <td><font face="vazir" size=3>دمای واقعی اندازه‌گیری شده در آن روزدمای واقعی اندازه‌گیری شده در آن روز</td>
</tr>
    
<tr>
    <td><font face="vazir" size=3>t2</td>
    <td><font face="vazir" size=3>میانگین دمایی که مشتریان احساس کرده‌اند</td>
</tr>
    
<tr>
    <td><font face="vazir" size=3>humidity</td>
    <td><font face="vazir" size=3>رطوبت هوا در آن روز</td>
</tr>
    
<tr>
    <td><font face="vazir" size=3>wind_speed</td>
    <td><font face="vazir" size=3>سرعت باد در آن روز</td>
</tr>
    
<tr>
    <td><font face="vazir" size=3>is_weekend</td>
    <td><font face="vazir" size=3>آیا آن روز، روز غیر کاری است یا خیر</td>
</tr>
    
<tr>
    <td><font face="vazir" size=3>season</td>
    <td><font face="vazir" size=3>فصل چندم سال است</td>
</tr>

</table>
</p>

In [3]:
df = pd.read_csv('bikes_borrowed.csv')
df.head()

   cnt   t1   t2  humidity  wind_speed  is_weekend  season
0  182  3.0  2.0      93.0         6.0         1.0     3.0
1  138  3.0  2.5      93.0         5.0         1.0     3.0
2  134  2.5  2.5      96.5         0.0         1.0     3.0
3   72  2.0  2.0     100.0         0.0         1.0     3.0
4   47  2.0  0.0      93.0         6.5         1.0     3.0

<p dir=rtl style="direction: rtl;text-align: right;line-height:200%;font-family:vazir;font-size:medium">
<font face="vazir" size=3>
    نحوه‌ی کار با تابع <code>read_csv</code> را در درسنامه‌های آینده یاد می‌گیرید؛ اما به استفاده از <code>head</code> در این کد دقت کنید؛ همان‌طور که گفتیم، این تابع به طور پیش‌فرض، ۵ داده‌ی بالای دیتافریم را به ما نشان می‌دهد.
</font>
</p>

<h2 align=right style="line-height:200%;font-family:vazir;color:#0099cc">
<font face="vazir" color="#0099cc">
قسمت اول
    </font>
</h2>

<p dir=rtl style="direction: rtl;text-align: right;line-height:200%;font-family:vazir;font-size:medium">
<font face="vazir" size=3>
    همان‌طور که می‌بینید نام ستون‌های <code>t1</code> و <code>t2</code> خیلی کلی است و در مورد مقدار آن‌ها نکته جالبی را نشان نمی‌دهد به همین دلیل خوب است تا آن‌ها را <code>rename</code> کنیم.
<br>
    در سلول زیر، نام ستون <code>t1</code> را به <code>t_real</code> و نام ستون <code>t2</code> را به <code>t_feels_like</code> تغییر دهید.
<br>
    برای تغییر نام نمایه‌ها یا ستون‌ها می‌توانیم از تابع <code>rename</code> مانند کد زیر استفاده کنیم:
<br>
</font>
</p>

`df.rename(columns={"col1": "new_col1", "col2": "new_col2"} , inplace = True)`

In [4]:
df.rename(columns={"t1": "t_real","t2":"t_feels_like"}, inplace= True)
df

        cnt  t_real  t_feels_like  humidity  wind_speed  is_weekend  season
0       182     3.0           2.0      93.0         6.0         1.0     3.0
1       138     3.0           2.5      93.0         5.0         1.0     3.0
2       134     2.5           2.5      96.5         0.0         1.0     3.0
3        72     2.0           2.0     100.0         0.0         1.0     3.0
4        47     2.0           0.0      93.0         6.5         1.0     3.0
...     ...     ...           ...       ...         ...         ...     ...
17409  1042     5.0           1.0      81.0        19.0         0.0     3.0
17410   541     5.0           1.0      81.0        21.0         0.0     3.0
17411   337     5.5           1.5      78.5        24.0         0.0     3.0
17412   224     5.5           1.5      76.0        23.0         0.0     3.0
17413   139     5.0           1.0      76.0        22.0         0.0     3.0

[17414 rows x 7 columns]

<p dir=rtl style="direction: rtl;text-align: right;line-height:200%;font-family:vazir;font-size:medium">
<font face="vazir" size=3>
    به پارامتر <code>inplace = True</code> دقت کنید؛ وجود این پارامتر باعث می‌شود که تابع <code>rename</code>، به جای آن که دیتافریم را کپی کرده و بعد از اعمال تغییرات خروجی دهد، تغییرات را مستقیما روی دیتافریم اصلی اعمال کند.
<br>
برای درک بهتر این موضوع می‌توانید با حذف این پارامتر متوجه تغییر در نحوه‌ی کارکرد این تابع بشوید.
</font>
</p>

<h2 align=right style="line-height:200%;font-family:vazir;color:#0099cc">
<font face="vazir" color="#0099cc">
قسمت دوم
    </font>
</h2>

<p dir=rtl style="direction: rtl;text-align: right;line-height:200%;font-family:vazir;font-size:medium">
<font face="vazir" size=3>
از آن‌جایی که اغلب روز‌هایی که دوچرخه سواران به هوا اعتراض می‌کنند روز‌های بادی است، یوسف تصمیم گرفت که محاسبات را فقط برای روز‌هایی که سرعت باد بیشتر از ۱۰ است انجام دهد.
<br>
    بنابراین در دیتافریم <code>windy_days_df</code>، تنها داده‌هایی را ذخیره کنید که سرعت باد، بزرگتر از ۱۰ باشد.
</font>
</p>

In [5]:
windy_days_df = df[df.wind_speed > 10]
windy_days_df

        cnt  t_real  t_feels_like  humidity  wind_speed  is_weekend  season
10      528     3.0          -0.5      93.0        12.0         1.0     3.0
11      727     2.0          -1.5     100.0        12.0         1.0     3.0
12      862     2.0          -1.5      96.5        13.0         1.0     3.0
13      916     3.0          -0.5      87.0        15.0         1.0     3.0
15      869     2.0          -1.5      93.0        11.0         1.0     3.0
...     ...     ...           ...       ...         ...         ...     ...
17409  1042     5.0           1.0      81.0        19.0         0.0     3.0
17410   541     5.0           1.0      81.0        21.0         0.0     3.0
17411   337     5.5           1.5      78.5        24.0         0.0     3.0
17412   224     5.5           1.5      76.0        23.0         0.0     3.0
17413   139     5.0           1.0      76.0        22.0         0.0     3.0

[12595 rows x 7 columns]

<h2 align=right style="line-height:200%;font-family:vazir;color:#0099cc">
<font face="vazir" color="#0099cc">
قسمت سوم
    </font>
</h2>

<p dir=rtl style="direction: rtl;text-align: right;line-height:200%;font-family:vazir;font-size:medium">
<font face="vazir" size=3>
برای انجام باقی محاسبات فقط ستون‌های مخصوص دما را نیاز داریم؛ پس برای دیتافریم <code>windy_days_df</code>، ستون‌های <code>humidity</code> , <code>t_feels_like</code> , <code>t_real</code> و <code>wind_speed</code> را ذخیره کرده و باقی ستون‌ها را نادیده بگیرید.

</font>
</p>

In [6]:
windy_days_df = windy_days_df[["t_real","t_feels_like","humidity","wind_speed"]]

<p dir=rtl style="direction: rtl;text-align: right;line-height:200%;font-family:vazir;font-size:medium">
<font face="vazir" size=3>
در مراحل بعدی می‌خواهیم برخی مقادیر دیتافریم را تغییر دهیم پس برای آن‌که دیتافریم اصلی و <code>windy_days_df</code> تغییر نکنند لازم است تا از تابع <code>copy</code> استفاده کنیم.
<br>
به طور کلی استفاده از مساوی برای دیتافریم‌ها در پانداز مانند نامپای عمل می‌کنند و تنها یک رفرنس جدید به همان دیتافریم اضافه می‌شود بنابراین تغییر دادن هر کدام از دیتافریم‌ها باعث تغییر دیگری نیز می‌شود.
<br>
    استفاده از تابع <code>copy</code> این قابلیت را برای ما ایجاد می‌کند که یک کپی از دیتافریم اولیه دریافت کنیم و تغییر یکی تاثیری روی دیگری نداشته باشد.
<br>
در ادامه این ویژگی را بیشتر بررسی می‌کنیم اما فعلا برای ادامه، سلول زیر را اجرا کنید.
</font>
</p>

In [7]:
temperature_df = windy_days_df.copy()

<h2 align=right style="line-height:200%;font-family:vazir;color:#0099cc">
<font face="vazir" color="#0099cc">
قسمت چهارم
    </font>
</h2>

<p dir=rtl style="direction: rtl;text-align: right;line-height:200%;font-family:vazir;font-size:medium">
<font face="vazir" size=3>
یوسف برای انجام تحلیل‌های خود نیاز دارد بداند که یک روز نسبت به بازده کلی دما چقدر گرم است. برای این کار مراحل زیر را به ترتیب انجام دهید:
<br>
راهنمایی: تمام عملیات این مرحله را می‌توانید با توابع نامپای انجام دهید. همان طور که گفتیم پانداز بر اساس نامپای نوشته شده است پس تمامی عملیات نامپای در این‌جا هم قابل استفاده است.
<br>
    ۱- در متغیر <code>t_max</code> مقدار ماکزیمم ستون <code>t_real</code> را ذخیره کنید.
<br>
    ۲- در متغیر <code>t_min</code> مقدار مینیمم ستون <code>t_real</code> را ذخیره کنید.
<br>
۳- در خط سوم، ستون جدیدی به دیتافریم اضافه می‌کنیم. در این ستون از فرمول زیر برای نرمال سازی و پیدا کردن دمای نسبی استفاده کنید.
<br>
</font>
</p>

‍‍`((temp - min) / (max - min)) * 100`

In [8]:
#using numpy on df
t_max = np.max(temperature_df.t_real)
t_min = np.min(temperature_df.t_real)
temperature_df['t_percent'] = ((temperature_df.t_real - t_min)/(t_max - t_min)) * 100
temperature_df

       t_real  t_feels_like  humidity  wind_speed  t_percent
10        3.0          -0.5      93.0        12.0  11.428571
11        2.0          -1.5     100.0        12.0   8.571429
12        2.0          -1.5      96.5        13.0   8.571429
13        3.0          -0.5      87.0        15.0  11.428571
15        2.0          -1.5      93.0        11.0   8.571429
...       ...           ...       ...         ...        ...
17409     5.0           1.0      81.0        19.0  17.142857
17410     5.0           1.0      81.0        21.0  17.142857
17411     5.5           1.5      78.5        24.0  18.571429
17412     5.5           1.5      76.0        23.0  18.571429
17413     5.0           1.0      76.0        22.0  17.142857

[12595 rows x 5 columns]

<h2 align=right style="line-height:200%;font-family:vazir;color:#0099cc">
<font face="vazir" color="#0099cc">
قسمت پنچم
    </font>
</h2>

<p dir=rtl style="direction: rtl;text-align: right;line-height:200%;font-family:vazir;font-size:medium">
<font face="vazir" size=3>
حال برای پیش‌بینی دمایی که احساس می‌شود مقدار این ستون را عوض می‌کنیم.
<br>
برای مقداردهی این ستون از فرمول زیر استفاده کنید:
<br>
</font>
</p>

`t_feels_like = t_real + (humidity * t_real)/1000 - (wind_speed)/10 -2` 
<br>
<p dir=rtl style="direction: rtl;text-align: right;line-height:200%;font-family:vazir;font-size:medium">
<font face="vazir" size=3>
یادآوری: هر ستون دیتافریم را می‌توانید مانند یک سری جدا کرده و مانند یک ارایه‌ی نامپای با آن رفتار کنید.
</font>
</p>

In [9]:
temperature_df['t_feels_like'] = temperature_df.t_real + ((temperature_df.humidity * temperature_df.t_real) / 1000) - ((temperature_df.wind_speed)/10) - 2
temperature_df

       t_real  t_feels_like  humidity  wind_speed  t_percent
10        3.0       0.07900      93.0        12.0  11.428571
11        2.0      -1.00000     100.0        12.0   8.571429
12        2.0      -1.10700      96.5        13.0   8.571429
13        3.0      -0.23900      87.0        15.0  11.428571
15        2.0      -0.91400      93.0        11.0   8.571429
...       ...           ...       ...         ...        ...
17409     5.0       1.50500      81.0        19.0  17.142857
17410     5.0       1.30500      81.0        21.0  17.142857
17411     5.5       1.53175      78.5        24.0  18.571429
17412     5.5       1.61800      76.0        23.0  18.571429
17413     5.0       1.18000      76.0        22.0  17.142857

[12595 rows x 5 columns]

<p dir=rtl style="direction: rtl;text-align: right;line-height:200%;font-family:vazir;font-size:medium">
<font face="vazir" size=3>
    همان‌طور که می‌بینید مقدار ستون <code>t_feels_like</code> تغییر کرده و دیگر مانند آن‌چه در دیتافریم اولیه داشتیم نیست. حال بیایید کارکرد تابع ‍<code>copy</code> را بررسی کنیم. اگر تمام مراحل را درست پیش رفته باشید، مقدار ستون <code>t_feels_like</code> در دیتافریم ‍‍<code>windy_days_df</code> نباید تغییر کرده باشد. برای اطمینان از این موضوع با استفاده از تابع <code>head</code> در کد بالا می‌توانید مقادیر این دو دیتافریم را مقایسه کنید.

</font>
</p>

<h2 align=right style="line-height:200%;font-family:vazir;color:#0099cc">
<font face="vazir" color="#0099cc">
قسمت ششم
    </font>
</h2>

<p dir=rtl style="direction: rtl;text-align: right;line-height:200%;font-family:vazir;font-size:medium">
<font face="vazir" size=3>
در نهایت یوسف که به پیش بینی اولیه‌ای از دمایی که مشتریان احساس خواهند کرد رسید می‌خواهد دقت این تابع را بررسی کند. برای این کار از فرمول mean_absolut_error یا MAE استفاده می‌کنیم که به صورت زیر است:
<br>
</font>
</p>

`np.mean(np.abs(temperature_df['t_feels_like'] - windy_days_df['t_feels_like']))`
<br>
<p dir=rtl style="direction: rtl;text-align: right;line-height:200%;font-family:vazir;font-size:medium">
<font face="vazir" size=3>
    این مقدار را محاسبه و در متغیر <code>diffrence</code> ذخیره کنید.
</font>
</p>

In [10]:
diffrence = np.mean(np.abs(temperature_df['t_feels_like'] - windy_days_df['t_feels_like']))

<h2 align=right style="line-height:200%;font-family:vazir;color:#0099cc">
<font face="vazir" color="#0099cc">
قسمت هفتم
    </font>
</h2>

<p dir=rtl style="direction: rtl;text-align: right;line-height:200%;font-family:vazir;font-size:medium">
<font face="vazir" size=3>
    در این تمرین با تابع <code>head(n)</code> کار کردیم اما بیایید به بررسی عمیق‌تر این تابع بپردازیم.
<br>
به طور کلی این تابع برای نمایش فقط استفاده نمی‌شود بلکه اعمال آن روی دیتافریم یک کپی از n داده‌ی اول آن را برمی‌گرداند و می‌توان آن را در دیتافریم‌های دیگری ذخیره کرد.
<br>
    در دیتافریم زیر، ۱۰۰ داده‌ی اول دیتافریم <code>temperature_df</code> را ذخیره کنید.
</font>
</p>

In [11]:
final_df = temperature_df.head(100)

<h2 align=right style="line-height:200%;font-family:vazir;color:#0099cc">
<font face="vazir" color="#0099cc">
<b>سلول جواب‌ساز</b>
</font>
</h2>

In [12]:
import zlib
import zipfile

np.savez("answers.npz",diffrence = diffrence, t_min = t_min , t_max = t_max)

def compress(file_names):
    print("File Paths:")
    print(file_names)
    compression = zipfile.ZIP_DEFLATED
    with zipfile.ZipFile("result.zip", mode="w") as zf:
        for file_name in file_names:
            zf.write('./' + file_name, file_name, compress_type=compression)


df.to_csv('bikes.csv',index = True)
windy_days_df.to_csv('windy_days.csv',index = True)
temperature_df.to_csv("temperature.csv", index = True)
final_df.to_csv("final.csv", index = True)

file_names = ["bikes.csv", "mad_cyclists.ipynb","windy_days.csv","temperature.csv", "final.csv", "answers.npz"]
compress(file_names)

File Paths:
['bikes.csv', 'mad_cyclists.ipynb', 'windy_days.csv', 'temperature.csv', 'final.csv', 'answers.npz']